version: '3.8'

services:
  portal_fornecedor_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portal_fornecedor_web
    ports:
      - "3001:3000"
    networks:
      - traefik
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fornecedor.rule=Host(`fornecedor.nelfarma.dev.br`)"
      - "traefik.http.routers.fornecedor.entrypoints=websecure"
      - "traefik.http.routers.fornecedor.tls.certresolver=cloudflare"
      - "traefik.http.services.fornecedor.loadbalancer.server.port=3000"
      - "traefik.http.routers.fornecedor.middlewares=headers-seguranca"

networks:
  traefik:
    external: true

  app-network:
    driver: bridge